title: Stop and Search
baseurl: "/stop-and-search" # the subpath of your site, e.g. /blog
url: "https://mysociety.github.io" # the base hostname & protocol for your site, e.g. http://example.com
host: 0.0.0.0

exclude:
  - .browserlistrc
  - .sass-cache/
  - .jekyll-cache/
  - bin/
  - config/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - Makefile
  - node_modules/
  - package.json
  - package-lock.json
  - Procfile.dev
  - Rakefile
  - README.md
  - script/
  - ssl/
  - static/css/
  - tmp/
  - vendor/
  - vite.config.js

plugins:
  - jekyll/vite
